# docker-compose.yml
version: "3.8"

services:
  vite-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:80" # 主机 Nginx 会代理到这个端口
    container_name: vite-react-app
    restart: unless-stopped
