# docker-compose.yml
version: "3.8"

services:
  vite-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:80" # Map Nginx port to localhost port
    container_name: vite-react-app
    restart: unless-stopped
